#!/bin/bash
source scp.conf

HEIGHT=20
CHOICE_HEIGHT=10
WIDTH=78
BACKTITLE="SMILEYS CONTROL PANEL"
TITLE="[C O N T R O L - P A N E L]"
MENU="What would you like to do?"

OPTIONS=(
1		"System Control Panel"
2		"Plex Control Panel"
3		"Samba Control Panel"
4		"VSFTPD Control Panel"
5		"SSH Control Panel"
6		"Network Security"
7		"OpenVPN Control Panel"
8		"Permissions Control Panel"
9		"Backup & Setup"
10		"Uninstall Smileys Control Panel"
)

CHOICE=$(dialog --clear \
    --backtitle "$BACKTITLE" \
    --title "$TITLE" \
    --menu "$MENU" \
    $HEIGHT $WIDTH $CHOICE_HEIGHT \
    "${OPTIONS[@]}" \
    2>&1 >/dev/tty)

clear
case $CHOICE in
    1)
	/scripts/system
        ./SCP
        ;;

    2)
    	scripts/plex
    	./SCP
    	;;

    3)
    	scripts/smb
    	./SCP
    	;;

    4)
    	scripts/vsftpd
    	./SCP
    	;;
    
    5)
    	scripts/ssh
    	./SCP
    	;;

    6)
    	if [ -x "$(command -v ufw)" ]
	then
		scripts/ufw
	elif [ -x "$(command -v firewalld)" ]
	then
		scripts/firewalld
	fi
    	./SCP
    	;;
    
    7)
    	scripts/openvpn
    	./SCP
    	;;


    8)
	scripts/permissions
	./SCP
	;;

    9)
    	scripts/backupinit
    	./SCP
    	;;

    10)
    	echo "*** WARNING THIS WILL DELETE ALL SCP FILES!!!***"
    	echo "Press ENTER to Uninstall, Otherwise press CTRL + C to exit"
    	read ENTER
    	sudo rm -rfv /etc/smiley-scp
    	sudo rm -fv /bin/smiley-scp
    	sudo rm -fv /usr/local/share/man/man1/smiley-scp.1
    	sudo rm -rfv /var/log/smiley-ip.log
    	
esac
