." Process this file with
." groff -man -Tascii smiley-scp.1
."
.TH smiley-scp

.Sh NAME
.B smiley-scp
- Dialog user interface to manage different systems of linux.

.SH SYNOPSIS
.B smiley-scp

.SH DESCRIPTION
.B smiley-scp
is a CLI dialog user interface to manage different systems of linux such as firewallD, UFW, Updating the system, Managing OpenVPN, Plex, Samba, VSFTPD, SSH, viewing disk utilization, managing permissions, power management, and viewing a tmux split between htop and nload.

.SH FILES
.TP
.I
/etc/smiley-scp/scp.conf
.TP
.I
/bin/smiley-scp

.SH COPYRIGHT
.PP
Copyright 2020 Smiley McSmiles. All rights reserved
https://www.github.com/Smiley-McSmiles/SCP

.SH CREDITS
.PP
This man page was created by Smiley McSmiles <SmileyMcSmiles@ProtonMail.com>
