#!/bin/bash

#Dialog checklist for 1 Removing the old backup and 2 creating a backup of /var/lib/plexmediaserver
#============================
checklistChoice="$(dialog --stdout --checklist "Select items with SPACEBAR:" 0 0 0 \
  1 "Remove the old backups?" off \
  2 "Backup /var/lib/plex?" off )"
clear
#============================
#if then checklist data
#===================
if [[ $checklistChoice == *1* ]]; then
	rm -rfv ~/smiley-scp-backup
fi

if [[ $checklistChoice == *2* ]]; then
	echo Copying Plex Server Settings...
	mkdir ~/smiley-scp-backup
	mkdir ~/smiley-scp-backup/plex
	cd /var/lib
	sudo time tar cvf ~/smiley-scp-backup/plex/plexbackup.tar plex*
	cd /etc/smiley-scp
	sudo chown -fv $USER:$USER ~/smiley-scp-backup/plex/plexbackup.tar
	sudo chmod -fv 770 ~/smiley-scp-backup/plex/plexbackup.tar
fi
clear
#===================


echo Copying all necessary config files...

echo Copying Smileys Configuration File
sudo cp -fv /etc/smiley-scp/scp.conf ~/smiley-scp-backup/

echo Copying Samba Configuration...
sudo cp -fv /etc/samba/smb.conf ~/smiley-scp-backup/

echo Copying VSFTPD Configuration...
sudo cp -fv /etc/vsftpd.conf ~/smiley-scp-backup/
sudo cp -fv /etc/vsftpd.userlist ~/smiley-scp-backup/

echo Copying SSHD Configuration...
sudo cp -fv /etc/ssh/sshd_config ~/smiley-scp-backup/

if [ -x "$(command -v ufw)" ]
	then
		echo Copying FireWall Configuration...
		sudo cp -fv /etc/ufw/user*.rules ~/smiley-scp-backup/

elif [ -x "$(command -v firewalld)" ]
	then
		echo Copying FireWall Configuration...
		sudo cp -fv /etc/firewalld/zones/FedoraWorkstation.xml ~/smiley-scp-backup/ 
fi

sudo chown -Rfv $USER:users ~/smiley-scp-backup/
sudo chmod -Rfv 770 ~/smiley-scp-backup/

echo Done backing up..
echo Your backup is located at ~/smiley-scp-backup
sleep 1
echo Press ENTER to exit
read ENTER
