#!/bin/bash

#Dialog checklist for 1 Removing the old backup and 2 creating a backup of /var/lib/plexmediaserver
#============================
checklistChoice="$(dialog --stdout --checklist "Select items with SPACEBAR:" 0 0 0 \
  1 "Remove the old backups?" off \
  2 "Backup /var/lib/plex?" off )"
#============================

#if then checklist data
#===================
if [[ $checklistChoice == *1* ]]; then
	rm -rfv backup
fi

if [[ $checklistChoice == *2* ]]; then
	echo Copying Plex Server Settings...
	mkdir backup
	mkdir backup/plex
	scpDirectory=`pwd`
	cd /var/lib
	sudo time tar cvf $scpDirectory/backup/plex/plexbackup.tar plex*
	cd $scpDirectory
	sudo chown -fv $USER:$USER backup/plex/plexbackup.tar
	sudo chmod -fv 770 backup/plex/plexbackup.tar
fi
clear
#===================


echo Copying all necessary config files...
echo Copying Samba Configuration...
sudo cp -fv /etc/samba/smb.conf backup/

echo Copying VSFTPD Configuration...
sudo cp -fv /etc/vsftpd.conf backup/
sudo cp -fv /etc/vsftpd.userlist backup/

echo Copying SSHD Configuration...
sudo cp -fv /etc/ssh/sshd_config backup/

if [ -x "$(command -v ufw)" ]
	then
		echo Copying FireWall Configuration...
		sudo cp -fv /etc/ufw/user*.rules backup/

elif [ -x "$(command -v firewalld)" ]
	then
		echo Copying FireWall Configuration...
		sudo cp -fv /etc/firewalld/zones/FedoraWorkstation.xml backup/ 
fi

sudo chown -Rfv $USER:users backup
sudo chmod -Rfv 770 backup

echo Done backing up..
sleep 1
echo Press ENTER to exit
read ENTER
