#!/bin/bash
remoteIp=`dig +short myip.opendns.com @resolver1.opendns.com`
timeOfRelease=`date`
geolocation=`geoiplookup $remoteIp`
echo "$timeOfRelease" >> /var/log/smiley-ip.log
echo "$remoteIp" >> /var/log/smiley-ip.log
echo "$geolocation" >> /var/log/smiley-ip.log

sleep 60
screen -d -m -S iplogger scripts/iplogger

