#!/bin/bash
while true; do 
remoteIp=`dig +short myip.opendns.com @resolver1.opendns.com`
timeOfRelease=`date`
geolocation=`geoiplookup $remoteIp`
echo "$timeOfRelease    $remoteIp    $geolocation" >> /var/log/smiley-ip.log
sleep 60
done
