#!/bin/bash
HEIGHT=20
CHOICE_HEIGHT=5
WIDTH=78
BACKTITLE="SMILEYS CONTROL PANEL"
TITLE="[P O W E R  M A N A G E M E N T]"
MENU="What would you like to do?"

OPTIONS=(
1				"Restart Server"
2				"Update and Restart"
3				"Power Off Server"
4				"Update and Power Off Server"
5				"MAIN MENU"
)

CHOICE=$(dialog --clear \
    --backtitle "$BACKTITLE" \
    --title "$TITLE" \
    --menu "$MENU" \
    $HEIGHT $WIDTH $CHOICE_HEIGHT \
    "${OPTIONS[@]}" \
    2>&1 >/dev/tty)

clear
case $CHOICE in
    1)
        sudo reboot
        ;;

    2)
        sudo pacman -Syu && sudo reboot
    	;;

    3)
    	sudo poweroff
    	;;
    
    4)
        sudo pacman -Syu && sudo poweroff
    	;;

    5)
    	./SCP
    	;;

esac
