#!/bin/bash
HEIGHT=0
CHOICE_HEIGHT=0
WIDTH=78
BACKTITLE="SMILEYS CONTROL PANEL"
TITLE="[P O W E R  M A N A G E M E N T]"
MENU="What would you like to do?"

OPTIONS=(
1				"Restart Server"
2				"Update and Restart"
3				"Power Off Server"
4				"Update and Power Off Server"
5				"MAIN MENU"
)

CHOICE=$(dialog --clear \
    --backtitle "$BACKTITLE" \
    --title "$TITLE" \
    --menu "$MENU" \
    $HEIGHT $WIDTH $CHOICE_HEIGHT \
    "${OPTIONS[@]}" \
    2>&1 >/dev/tty)

clear
case $CHOICE in
    1)
        sudo reboot
        ;;

    2)
        if [ -x "$(command -v apt)" ];	     then sudo apt update && sudo apt upgrade
		elif [ -x "$(command -v dnf)" ];     then sudo dnf upgrade
		elif [ -x "$(command -v yum)" ];     then sudo yum update && sudo yum upgrade
		elif [ -x "$(command -v zypper)" ];  then sudo zypper ref && sudo zypper up
		elif [ -x "$(command -v pacman)" ];  then sudo pacman -Syu
		else echo "FAILED TO UPDATE PACKAGES">&2; fi
    	sudo reboot
    	;;

    3)
    	sudo poweroff
    	;;
    
    4)
        if [ -x "$(command -v apt)" ];	     then sudo apt update && sudo apt upgrade
		elif [ -x "$(command -v dnf)" ];     then sudo dnf upgrade
		elif [ -x "$(command -v yum)" ];     then sudo yum update && sudo yum upgrade
		elif [ -x "$(command -v zypper)" ];  then sudo zypper ref && sudo zypper up
		elif [ -x "$(command -v pacman)" ];  then sudo pacman -Syu
		else echo "FAILED TO UPDATE PACKAGES">&2; fi
		sudo poweroff
    	;;

    5)
    	./SCP
    	;;

esac
