#!/bin/bash
#Checklist Options
#============================
checklistChoice="$(dialog --stdout --checklist "Select items with SPACEBAR:" 0 0 0 \
  1 "Restore plexbackup.tar" off \
  2 "Install Samba VSFTPD" off \
  3 "Restore backup configuration files" off \
  4 "Enable Samba" off \
  5 "Enable VSFTPD" off \
  6 "Create Samba user" off \
  7 "Install Plex Media Server" off \
  8 "Create scp.conf" off \
  9 "Restore OpenVPN" off )"
clear
#============================
#1 Restore Plex meta-data
#======================
if [[ $checklistChoice == *1* ]]; then
	sudo tar xvf ~/smiley-scp-backup/plex/plexbackup.tar -C /
fi
#======================
#2 Install samba and VSFTPD
#======================
if [[ $checklistChoice == *2* ]]; then
packagesNeeded='samba vsftpd'
if [ -x "$(command -v apt)" ];	 then sudo apt install ufw $packagesNeeded
elif [ -x "$(command -v dnf)" ];     then sudo dnf install $packagesNeeded
elif [ -x "$(command -v yum)" ];     then sudo yum install $packagesNeeded
elif [ -x "$(command -v zypper)" ];  then sudo zypper install $packagesNeeded
elif [ -x "$(command -v pacman)" ];  then sudo pacman -Syu ufw $packagesNeeded
else echo "FAILED TO INSTALL PACKAGES: Package manager not found. You must manually install: $packagesNeeded">&2; fi
fi
#======================
#3 Copy over backed up configuration files.
#======================
if [[ $checklistChoice == *3* ]]; then
	echo Installing all necessary config files...
	sleep 3
	echo Installing Samba Configuration...
	sleep 1
	sudo cp -fv ~/smiley-scp-backup/smb.conf /etc/samba/
	sudo chown -fv root:root /etc/samba/smb.conf
	
	echo Copying Smileys Configuration File
	sudo cp -fv ~/smiley-scp-backup/scp.conf /etc/smiley-scp/
	sudo chmod -fv 776 /etc/smiley-scp/scp.conf

	echo Copying OpenVPN Configuration Files
	sudo cp -fv ~/smiley-scp-backup/ovpn.conf /etc/smiley-scp/
	sudo rm -rfv /etc/openvpn
	sudo cp -rfv ~/smiley-scp-backup/openvpn /etc/
	sudo chown -Rfv root:openvpn /etc/openvpn
	sudo chmod -Rfv 440 /etc/openvpn

	echo Installing VSFTPD Configuration...
	sleep 1
	sudo cp -fv ~/smiley-scp-backup/vsftpd.conf /etc/vsftpd/
	sudo cp -fv ~/smiley-scp-backup/user_list /etc/vsftpd/
	sudo chown -Rfv root:root /etc/vsftpd

	if [ -x "$(command -v ufw)" ]
		then
			echo Installing FireWall Configuration...
			sleep 1
			sudo cp -fv ~/smiley-scp-backup/user*.rules /etc/ufw/
			sudo chown -fv root:root /etc/ufw/user*.rules

			echo Enabling UFW FireWall...
			sleep 1
			sudo ufw enable

	elif [ -x "$(command -v firewalld)" ]
		then
			echo Installing FireWall Configuration...
			sleep 1
			sudo cp -fv ~/smiley-scp-backup/*.xml /etc/firewalld/zones/
			sudo chown -fv root:root /etc/firewalld/zones/*.xml
			sudo chmod -fv 700 /etc/firewalld/zones/*.xml
			echo Reloading Firewalld
			sleep 1
			sudo firewall-cmd --reload
	fi
fi
#======================
#4 Enable Samba
#==============
if [[ $checklistChoice == *4* ]]; then
	echo "Enabling Samba..."
	sudo systemctl enable smb nmb
	sudo systemctl restart smb nmb
fi
#==============
#5 Enable VSFTPD
#===============
if [[ $checklistChoice == *5* ]]; then
	sudo systemctl enable vsftpd.service
	sudo systemctl restart vsftpd.service
fi
#===============
#6 Create user for use with samba
#==============================
if [[ $checklistChoice == *6* ]]; then
	sharedusername="$(dialog --stdout --inputbox "Enter the Samba user:" 8 40)"
	shareddirectory="$(dialog --stdout --inputbox "Please enter the home directory for this new user:" 8 40)"
	sudo useradd -r -d $shareddirectory -m -U -G users $sharedusername
	echo Please enter the password for user $sharedusername
	sudo passwd $sharedusername

	if [ -x "$(command -v getenforce)" ]
		then
			echo Creating SELinux exception for $shareddirectory...
			sudo chcon -t samba_share_t $shareddirectory -R
	fi

	sleep 1
	echo Creating Samba user $sharedusername, please enter the samba password for Samba user $sharedusername.
	sudo smbpasswd -a $sharedusername
fi
#==============================
#7 Install plex
#==============
if [[ $checklistChoice == *7* ]]; then
	if [ -x "$(command -v rpm)" ]
		then
			sudo mkdir bin
			sudo rm -fv bin/*
			sudo wget -O bin/plex.rpm 'https://plex.tv/downloads/latest/5?channel=16&build=linux-x86_64&distro=redhat'
			sudo chmod a+x bin/*
			sudo dnf install -y bin/plex.rpm
			sudo rm -fv bin/*

	elif [ -x "$(command -v dpkg)" ]
		then
			sudo makdir bin
			sudo rm -fv bin/*
			sudo wget -O bin/plex.deb "https://plex.tv/downloads/latest/1?channel=16&build=linux-ubuntu-x86_64&distro=ubuntu&X-Plex-Token=removed"
			sudo chmod a+x bin/*
			sudo dpkg -i bin/plex.deb
			sudo rm -fv bin/*
		
	elif [ -x "$(command -v pacman)" ]
		then
			echo Installing Plex using yay -S plex-media-server-plexpass...
			sleep 3
			yay -S plex-media-server-plexpass
			sudo chown -Rfv plex:plex /var/lib/plex
			sudo systemctl stop plexmediaserver
			sudo systemctl start plexmediaserver
			echo Plex is done installing.

	else

	echo "***WARNING*** Couldn't figure out how to install Plex Media Server. Please seek documentation about Plex and your distrobution of Linux..."

	fi
dialog --title Information[!] --msgbox "Navigate to the Plex Web app to claim the server localhost:32400/web." 0 0
fi
#==============
#8 scp.conf setup
#==============
if [[ $checklistChoice == *8* ]]; then
	clear && pwd && ls -l
	rm -fv scp.conf
	touch scp.conf
	echo "sharedusername=$sharedusername" >> scp.conf
	echo "shareddirectory=$shareddirectory" >> scp.conf
	plexmediadirectory="$(dialog --stdout --inputbox "Please enter your Plex media directory:" 8 40)"
	echo "plexmediadirectory=$plexmediadirectory" >> scp.conf
fi
#================
#9 ovpn.conf OpenVPN
#================
if [[ $checklistChoice == *9* ]]; then
	sudo rm -rfv /etc/openvpn
	sudo cp -rfv ~/smiley-scp-backup/openvpn /etc/
	sudo chown -Rfv root:openvpn /etc/openvpn
	sudo chmod -Rfv 440 /etc/openvpn

	sudo systemctl enable openvpn-client@$defaultVPNConnection.service
	sudo systemctl start openvpn-client@$defaultVPNConnection.service
fi
#================
