#!/bin/bash
HEIGHT=0
CHOICE_HEIGHT=0
WIDTH=78
BACKTITLE="SMILEYS CONTROL PANEL"
TITLE="[S A M B A - C O N T R O L  P A N E L]"
MENU="What would you like to do?"

OPTIONS=(
1						"Check Samba Status-Simple"
2						"Check Samba Status-Detailed"
3						"Generate a new samba config"
4						"Edit smb.conf"
5               		"Start Samba"
6               		"Stop Samba"
7               		"Restart Samba"
8               		"MAIN MENU"
)

CHOICE=$(dialog --clear \
    --backtitle "$BACKTITLE" \
    --title "$TITLE" \
    --menu "$MENU" \
    $HEIGHT $WIDTH $CHOICE_HEIGHT \
    "${OPTIONS[@]}" \
    2>&1 >/dev/tty)

clear
case $CHOICE in
    1)
        sudo smbstatus
        echo
        smbd --version
        echo PRESS ENTER TO RETURN TO MENU
        read enter
        scripts/smb
        ;;

    2)
        smbd --version
        systemctl status smb nmb
        echo Press ENTER to exit.
        read enter
    	scripts/smb
    	;;
    	
    3)
		scripts/smbguided
    	scripts/smb
    	;;

    4)
    	sudo nano /etc/samba/smb.conf
    	scripts/smb
    	;;

    5)
    	systemctl start smb nmb
		systemctl enable smb nmb
        echo Done... Returning to menu...
        sleep 2
    	scripts/smb
    	;;

    6)
    	systemctl stop smb nmb
    	systemctl disable smb nmb
        echo Done... Returning to menu...
        sleep 2
    	scripts/smb
    	;;

    7)
    	systemctl restart smb nmb
        echo Done... Returning to menu...
        sleep 2
    	scripts/smb
    	;;

    8)
        ./SCP
        ;;
    	
esac
