#!/bin/bash
HEIGHT=0
CHOICE_HEIGHT=0
WIDTH=78
BACKTITLE="SMILEYS CONTROL PANEL"
TITLE="[S S H - C O N T R O L  P A N E L]"
MENU="What would you like to do?"

OPTIONS=(
1				"Check SSHD Status"
2				"Edit sshd_config"
3               		"Start SSHD"
4               		"Stop SSHD"
5               		"Restart SSHD"
6               		"MAIN MENU"
)

CHOICE=$(dialog --clear \
    --backtitle "$BACKTITLE" \
    --title "$TITLE" \
    --menu "$MENU" \
    $HEIGHT $WIDTH $CHOICE_HEIGHT \
    "${OPTIONS[@]}" \
    2>&1 >/dev/tty)

clear
case $CHOICE in
    1)
		sudo systemctl status sshd
        echo PRESS ENTER TO RETURN TO MENU
        read enter
        scripts/ssh
        ;;

    2)
	sudo nano /etc/ssh/sshd_config
    	scripts/ssh
    	;;

    3)
    	sudo systemctl enable sshd
    	sudo systemctl start sshd
        echo Done... Returning to menu...
        sleep 2
    	scripts/ssh
    	;;

    4)
    	sudo systemctl stop sshd
        echo Done... Returning to menu...
        sleep 2
    	scripts/ssh
    	;;

    5)
    	sudo systemctl restart sshd
        echo Done... Returning to menu...
        sleep 2
    	scripts/ssh
    	;;

    6)
        ./SCP
        ;;
    	
esac
